import type { Staff } from "./types";

// Supabase 未接続時のデモ表示用サンプルデータ（setup_guide.md の INSERT と同じ5名）
export const SAMPLE_STAFF: Staff[] = [
  {
    id: "sample-1",
    name: "山田 太郎",
    employee_number: "S001",
    department: "第一警備部",
    employment_type: "正社員",
    phone: "090-1234-5678",
    email: "yamada@example.com",
    address: "東京都千代田区丸の内 1-1-1",
    qualifications: ["施設警備2級"],
    rank: "隊長",
    days_off_preference: "毎週日曜",
    work_preference: "日勤希望",
    incompatible_staff_ids: null,
    available_shift_types: ["受付", "日勤"],
    fixed_off_weekdays: [0],
    shift_lean: "day",
    max_work_days: null,
    fixed_shift_type: "受付",
    join_date: "2020-04-01",
    leave_date: null,
    created_at: "2020-04-01T00:00:00Z",
    updated_at: "2020-04-01T00:00:00Z",
  },
  {
    id: "sample-2",
    name: "鈴木 一郎",
    employee_number: "S002",
    department: "第一警備部",
    employment_type: "正社員",
    phone: "090-2345-6789",
    email: "suzuki@example.com",
    address: "東京都江東区豊洲 2-3-4",
    qualifications: null,
    rank: "一般",
    days_off_preference: "",
    work_preference: "夜勤可",
    incompatible_staff_ids: null,
    available_shift_types: null,
    fixed_off_weekdays: null,
    shift_lean: "both",
    max_work_days: null,
    fixed_shift_type: null,
    join_date: "2021-04-01",
    leave_date: null,
    created_at: "2021-04-01T00:00:00Z",
    updated_at: "2021-04-01T00:00:00Z",
  },
  {
    id: "sample-3",
    name: "佐藤 花子",
    employee_number: "S003",
    department: "第二警備部",
    employment_type: "契約",
    phone: "090-3456-7890",
    email: "sato@example.com",
    address: "神奈川県横浜市西区みなとみらい 3-5-1",
    qualifications: ["交通誘導2級"],
    rank: "一般",
    days_off_preference: "第2・第4土曜",
    work_preference: "",
    incompatible_staff_ids: ["sample-5"],
    available_shift_types: null,
    fixed_off_weekdays: null,
    shift_lean: null,
    max_work_days: null,
    fixed_shift_type: null,
    join_date: "2022-06-01",
    leave_date: null,
    created_at: "2022-06-01T00:00:00Z",
    updated_at: "2022-06-01T00:00:00Z",
  },
  {
    id: "sample-4",
    name: "高橋 誠",
    employee_number: "S004",
    department: "第二警備部",
    employment_type: "正社員",
    phone: "090-4567-8901",
    email: "takahashi@example.com",
    address: "埼玉県さいたま市大宮区桜木町 4-2-1",
    qualifications: ["施設警備1級", "上級救命"],
    rank: "ベテラン",
    days_off_preference: "",
    work_preference: "",
    incompatible_staff_ids: null,
    available_shift_types: null,
    fixed_off_weekdays: null,
    shift_lean: null,
    max_work_days: null,
    fixed_shift_type: null,
    join_date: "2019-10-01",
    leave_date: null,
    created_at: "2019-10-01T00:00:00Z",
    updated_at: "2019-10-01T00:00:00Z",
  },
  {
    id: "sample-5",
    name: "中村 健二",
    employee_number: "S005",
    department: "第一警備部",
    employment_type: "パート",
    phone: "090-5678-9012",
    email: "nakamura@example.com",
    address: "千葉県千葉市中央区中央 5-1-2",
    qualifications: null,
    rank: "新人",
    days_off_preference: "土日希望",
    work_preference: "日勤のみ",
    incompatible_staff_ids: ["sample-3"],
    available_shift_types: ["日勤"],
    fixed_off_weekdays: [0, 6],
    shift_lean: "day",
    max_work_days: 20,
    fixed_shift_type: null,
    join_date: "2023-01-15",
    leave_date: null,
    created_at: "2023-01-15T00:00:00Z",
    updated_at: "2023-01-15T00:00:00Z",
  },
];
